services:
  - type: web
    name: spa
    env: static
    staticPublishPath: dist   # or build (React) / www (Angular)
    routes:
      - type: rewrite
        source: /*
        destination: /index.html